
export const JWT_PUBLIC_KEY = process.env.JWT_PUBLIC_KEY || `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoSJYhnHw/7qhkyODOw/V
2QXMDuLjV7um94euQVWoC+vwEXk/wLNSbqIsPYDNRJKaEGE7MoTH1lblcmivOGAc
05BBpGE7NRBnILb+Hf08PsJaC17nYwe3reVZcY0cor+UQLZZawJGbgs9kiUcV6jz
xrTwzlOhxH7hHdCCOf/j2pEwLkZwwmRlKvvuJ6LHKtrsoziERDQY4nY9Fe6A8WDV
adnueun7lpl24+xgTW9qmYXr9EBsi3YTTbUJGvKli+x9fbct/mDouBMxBA8igM6+
I2daZ7nKU5GKRu6xI98qODnbL9Ppw3RKljdkYwniWx5g1JfFublGUq9HqdbKkbq7
FwIDAQAB
-----END PUBLIC KEY-----
`;